{"data_mtime": 1620382847, "dep_lines": [1], "dep_prios": [5], "dependencies": ["builtins"], "hash": "612a2d86f5ceaba458f3772052dc88adf8da6a08f2afd5f84ad3db6a03883888", "id": "calculator.core.exceptions", "ignore_all": false, "interface_hash": "77cd56838674008eb56b6b242654bcf774de0d7279544bc3b4996679bebe175a", "mtime": 1620382015, "options": {"allow_redefinition": false, "allow_untyped_globals": false, "always_false": [], "always_true": [], "bazel": false, "check_untyped_defs": true, "disallow_any_decorated": false, "disallow_any_explicit": false, "disallow_any_expr": false, "disallow_any_generics": false, "disallow_any_unimported": false, "disallow_incomplete_defs": false, "disallow_subclassing_any": false, "disallow_untyped_calls": false, "disallow_untyped_decorators": false, "disallow_untyped_defs": false, "follow_imports": "normal", "follow_imports_for_stubs": false, "ignore_errors": false, "ignore_missing_imports": true, "implicit_reexport": true, "local_partial_types": false, "mypyc": false, "no_implicit_optional": false, "platform": "linux", "plugins": [], "show_none_errors": true, "strict_equality": false, "strict_optional": true, "strict_optional_whitelist": null, "warn_no_return": true, "warn_return_any": false, "warn_unreachable": false, "warn_unused_ignores": false}, "path": "./calculator/core/exceptions.py", "plugin_data": null, "size": 431, "suppressed": [], "version_id": "0.812"}